services:
  app_bundle.location.factory:
    class: AppBundle\Factory\LocationFactory

  app_bundle.crawler.provider:
    class: AppBundle\Crawler\CrawlerProvider
    arguments: [@app_bundle.location.factory]

  app_bundle.crawler.operator:
    class: AppBundle\Crawler\CrawlerOperator
    arguments: [@service_container]

  app_bundle.crawler.dispatcher:
    class: AppBundle\Crawler\CrawlerDispatcher
    factory_class: AppBundle\Crawler\CrawlerDispatcher
    factory_method: 'create'
    arguments: [@service_container]

  app_bundle.listener.routing_parameter:
    class: AppBundle\EventListener\RoutingParameterListener
    tags:
      - { name: kernel.event_subscriber }
